version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/bot
      - /app/node_modules
    depends_on:
      - db
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weekly_ranking
    volumes:
      - weekly-ranking-data:/var/lib/postgresql/data
volumes:
  weekly-ranking-data:
    external: true
